In [53]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
import pandas as pd

In [54]:
df = pd.DataFrame({'message':['ML is Subset of AI','AI is Superset of Both ML and DL ML and DL','GenAI is used to create or generate any type of content']})

In [63]:
df['data'] = df['message']
df['new'] =df['data']+' '+df['message']

df

,message,data,new
0,ML is Subset of AI,ML is Subset of AI,ML is Subset of AI ML is Subset of AI
1,AI is Superset of Both ML and DL ML and DL,AI is Superset of Both ML and DL ML and DL,AI is Superset of Both ML and DL ML and DL AI ...
2,GenAI is used to create or generate any type o...,GenAI is used to create or generate any type o...,GenAI is used to create or generate any type o...

In [56]:
vector = CountVectorizer(min_df=2)
val = vector.fit_transform(df['message'])
check = pd.DataFrame(val.toarray(),columns=vector.get_feature_names_out())
check

   ai  is  ml  of
0   1   1   1   1
1   1   1   2   1
2   0   1   0   1

In [57]:
vector = CountVectorizer()
val = vector.fit_transform(df['message'])
check = pd.DataFrame(val.toarray(),columns=vector.get_feature_names_out())
check

,ai,and,any,both,content,create,dl,genai,generate,is,ml,of,or,subset,superset,to,type,used
0,1,0,0,0,0,0,0,0,0,1,1,1,0,1,0,0,0,0
1,1,2,0,1,0,0,2,0,0,1,2,1,0,0,1,0,0,0
2,0,0,1,0,1,1,0,1,1,1,0,1,1,0,0,1,1,1

In [58]:
vector = CountVectorizer(min_df=2,max_df=3)
val = vector.fit_transform(df['message'])
check = pd.DataFrame(val.toarray(),columns=vector.get_feature_names_out())
check

   ai  is  ml  of
0   1   1   1   1
1   1   1   2   1
2   0   1   0   1

In [59]:
vector = CountVectorizer()
val = vector.fit_transform(df['message'])
check = pd.DataFrame(val.toarray(),columns=vector.get_feature_names_out())
check

,ai,and,any,both,content,create,dl,genai,generate,is,ml,of,or,subset,superset,to,type,used
0,1,0,0,0,0,0,0,0,0,1,1,1,0,1,0,0,0,0
1,1,2,0,1,0,0,2,0,0,1,2,1,0,0,1,0,0,0
2,0,0,1,0,1,1,0,1,1,1,0,1,1,0,0,1,1,1

In [60]:
vector.transform(['Art']).toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [61]:
vector.vocabulary_

{'ml': 10,
 'is': 9,
 'subset': 13,
 'of': 11,
 'ai': 0,
 'superset': 14,
 'both': 3,
 'and': 1,
 'dl': 6,
 'genai': 7,
 'used': 17,
 'to': 15,
 'create': 5,
 'or': 12,
 'generate': 8,
 'any': 2,
 'type': 16,
 'content': 4}

In [62]:
vector = TfidfVectorizer(stop_words='english',smooth_idf=True)
val = vector.fit_transform(df['message'])
check = pd.DataFrame(val.toarray(),columns=vector.get_feature_names_out())
check

,ai,content,create,dl,genai,generate,ml,subset,superset,type,used
0,0.517856,0.000000,0.000000,0.000000,0.000000,0.000000,0.517856,0.680919,0.000000,0.000000,0.000000
1,0.270720,0.000000,0.000000,0.711929,0.000000,0.000000,0.541440,0.000000,0.355964,0.000000,0.000000
2,0.000000,0.408248,0.408248,0.000000,0.408248,0.408248,0.000000,0.000000,0.000000,0.408248,0.408248